name: Code Review Workflow

on:
  push:
    branches:
      - master  # Ana dalınızı buraya yazın

jobs:
  code_review:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0.x'  # Kullandığınız .NET sürümünü belirtin

    - name: Restore dependencies
      run: dotnet restore

    - name: Build solution
      run: dotnet build --no-restore

    - name: Run code analysis
      env:
        OPENAI_API_KEY: ${{ secrets.FASTBUND }}  # OpenAI için oluşturduğunuz secret key
      run: |
        # Her katmandaki kod incelemesini yapmak için OpenAI API'yi çağırın
        for project in Core.Application Core.CrossCuttingConsern Core.Persistence; do
          dotnet run --project $project
        done
